# This is a basic workflow to help you get started with Actions

name: ReleaseBranch

on:
  workflow_dispatch:
    inputs:
      releasebranch:
        description: 'Release Branch Name'     
        required: true

jobs:
  release-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Merge staging -> release
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: staging
          target_branch: ${{ github.event.inputs.releaseBranch }}
          github_token: ${{ github.token }}
      - name: Merge activation -> release
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: activation
          target_branch: ${{ github.event.inputs.releaseBranch }}
          github_token: ${{ github.token }}      
