# This is a basic workflow to help you get started with Actions

name: ReleaseBranch

on:
  workflow_dispatch:
    inputs:
      releasebranch:
        description: 'Release Branch Name'     
        required: true

jobs:
  release-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: create branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ github.event.inputs.releaseBranch }}
      - name: staging > release
        uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: 'staging'
          target_branch: ${{ github.event.inputs.releaseBranch }}
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
      - name: activation > release
        uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: 'activation'
          target_branch: ${{ github.event.inputs.releaseBranch }}
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
