name: Release
on:
  push:
    branches:
      - staging
      - activation
      - money

jobs:
  release-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request to staging
        id: pull-staging
        uses: Elph/sync-branch@v1.1.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: ${{github.ref}}
          TO_BRANCH: "release"
          REVIEWERS: "Elph "
