name: Sync
on:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request to staging
        id: pull-staging
        uses: Elph/sync-branch@4cbfe7c91fa6614ef32c7f17cb7ce9312eb4c680
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "staging"
      - name: Opening pull request to money
        id: pull-money
        uses: Elph/sync-branch@4cbfe7c91fa6614ef32c7f17cb7ce9312eb4c680
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "money"
          REVIEWERS: "Elph"
          TEAM_REVIEWERS: "@elphnet/me"
      - name: Opening pull request to activation
        id: pull-activation
        uses: Elph/sync-branch@4cbfe7c91fa6614ef32c7f17cb7ce9312eb4c680
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "activation"
          REVIEWERS: "Elph"
